### PR TITLE
Multi set

### PR DESCRIPTION
**Pull request by ambs**
This is not yet complete. I want to continue updating the OO interface. 
But you can start giving it a look.

### CODE REVIEW

**Comment by ambs** [comment]
Wait for Travis, fix failures, and merge.
Will not work I/O at this time. More important features to look into.

**Comment by ambs** [comment]
in fact, I think he tests use some cache where files are missing :-)

**Comment by ambs** [comment]
can try to help starthing tuesday, I expect ;)

**Comment by leto** [comment]
@ambs ping...

**Comment by ambs** [comment]
sorry. Will try to get back into this.

**Comment by ambs** [comment]
and finally, all greeeeeen!

**Comment by leto** [comment]
Awesome!

**Pull request merged**
