### PR TITLE
Add docs and tests

### PR DESCRIPTION
**Pull request by ambs**

### CODE REVIEW

**Comment by leto** [comment]
@ambs thanks for this! Could you switch over to using the `ok_similar` function from Math::GSL::Test ?

**Comment by ambs** [comment]
How can I change the delta value on the comparison? It is requesting too much precision :-)

**Comment by leto** [comment]
@ambs `ok_similar($x,$y, $msg, $eps)` . The default `$eps` is 1e-8

**Comment by ambs** [comment]
Thanks and sorry for being lazy and not rtfm :)

**Comment by ambs** [comment]
Should be good now.
I didn't add tests to one function as the official manual doesn't present examples for it, and I preferred not to add a test than adding a test without math relevancy.

**Pull request merged**
