### PR TITLE
Bumps the version of Math/GSL.pm in preparation for the next CPAN release.

### PR DESCRIPTION
**Pull request by hakonhagland**
A resubmission of PR #199 that is rebased onto master branch

### CODE REVIEW

**Comment by leto** [comment]
@hakonhagland I vaguely remember the POD docs needing to manually update the version as well

**Comment by hakonhagland** [comment]
@leto I cannot find any version information in the POD. But I see that the `Changes` file needs to update. Strangely, the top entry in the `Changes` refers to version 0.41, even if the module `lib/Math/GSL.pm` says that it is 0.40. Maybe we should bump version to 0.42 instead of 0.41 then?

**Comment by leto** [comment]
@hakonhagland the changes file keeps track of things that will be in the next release, so it refers to 0.41

**Comment by leto** [comment]
I fixed the POD version

**Pull request closed without merging**
