### PR TITLE
Make compilation against GSL 2.3 & 2.4 succeed

### PR DESCRIPTION
**Pull request by djerius**
This patch includes the minimal changes to allow compilation under GSL 2.3 & GSL 2.4

### CODE REVIEW

**Comment by leto** [comment]
@djerius thanks for this! Have you tested compiling the code when older GSL versions are present, to make sure that still works? Looks like Travis CI is not happy: https://travis-ci.org/leto/math--gsl/builds/290065663

Looks like a great start, let me know how I can help you debug. I didn't even see these GSL releases come out 😸

**Comment by djerius** [comment]
> Have you tested compiling the code when older GSL versions are present, to make sure that still works? 

I was hoping that travis would do that, but that leads to your next statement:

> Looks like Travis CI is not happy: https://travis-ci.org/leto/math--gsl/builds/290065663

Travis isn't even getting to the module testing phase.  There's something in the setup which is giving it conniptions.  All of the tests fail with:

> git rev-parse master
> 
> fatal: Not a git repository (or any of the parent directories): .git
> 
> The command "./_travis/before_install.sh" failed and exited with 128 during .
> 
> Your build has been stopped.

I'm not at all familiar with travis, so help would be apprecited.

**Comment by anadon** [comment]
I'm running into odd things with this as well (#146 #147 ).  I think this does need some active attention and is related.

**Comment by leto** [comment]
@djerius it does seem that your patch makes the latest version work, but all previous versions are failing. When I looked on Travis, I saw this as one of the first errors:

```
xs/Integration_wrap.2.2.1.c:2045:5: error: ‘gsl_integration_fixed_legendre’ undeclared (first use in this function)
     gsl_integration_fixed_legendre = (gsl_integration_fixed_type *)(argp);
     ^

```
It may be that GSL upstream changed backward compatibility, I am not sure, things get really hairy if they did.

**Comment by djerius** [comment]
I've undoubtedly broken things, but since fixing the Travis configuration so testing against older versions worked I've had no time to look at this.  I'll find the time to split out the Travis fixes so that they can be applied to the master branch.

**Comment by djerius** [comment]
This is superseded by PR #158

**Pull request closed without merging**
